<a href="https://colab.research.google.com/github/Shreya-kudale-19/ml_basics-/blob/main/ML_using_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [175]:
import pandas as pd
import numpy as np
from urllib.request import urlretrieve

In [176]:
italy_covid_url = 'https://gist.githubusercontent.com/aakashns/f6a004fa20c84fec53262f9a8bfee775/raw/f309558b1cf5103424cef58e2ecb8704dcd4d74c/italy-covid-daywise.csv'

urlretrieve(italy_covid_url, 'italy-covid-daywise.csv') #trying to retrive the csv file attachted to the url

('italy-covid-daywise.csv', <http.client.HTTPMessage at 0x7e6d39dd4ad0>)

In [177]:
df = pd.read_csv('italy-covid-daywise.csv')

In [178]:
df

           date  new_cases  new_deaths  new_tests
0    2019-12-31        0.0         0.0        NaN
1    2020-01-01        0.0         0.0        NaN
2    2020-01-02        0.0         0.0        NaN
3    2020-01-03        0.0         0.0        NaN
4    2020-01-04        0.0         0.0        NaN
..          ...        ...         ...        ...
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    42583.0
245  2020-09-01      996.0         6.0    54395.0
246  2020-09-02      975.0         8.0        NaN
247  2020-09-03     1326.0         6.0        NaN

[248 rows x 4 columns]

In [179]:
df.describe()

         new_cases  new_deaths     new_tests
count   248.000000  248.000000    135.000000
mean   1094.818548  143.133065  31699.674074
std    1554.508002  227.105538  11622.209757
min    -148.000000  -31.000000   7841.000000
25%     123.000000    3.000000  25259.000000
50%     342.000000   17.000000  29545.000000
75%    1371.750000  175.250000  37711.000000
max    6557.000000  971.000000  95273.000000

In [180]:
df.columns

Index(['date', 'new_cases', 'new_deaths', 'new_tests'], dtype='object')

In [181]:
df['new_tests']

0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
        ...
243    53541.0
244    42583.0
245    54395.0
246        NaN
247        NaN
Name: new_tests, Length: 248, dtype: float64

this is a representation of how data is stored in the momery

In [182]:
covid_data_dict ={
    'date' : ['2020-08-30','2020-08-31','2020-09-01','2020-09-02','2020-09-03'],
    'new_cases' :[1444.0, 1365.0, 996.0, 975.0, 1326.0],
    'new_deaths' :[1,4,6,8,6],
    'new_tests': [53541.0,42583.0,54395.0,None,None]
}

In [183]:
res =covid_data_dict['new_cases']
type(res)

list

In [184]:
type(df)

pandas.core.frame.DataFrame

In [185]:
df['new_cases'][246]

np.float64(975.0)

In [186]:
df['new_tests'][243]

np.float64(53541.0)

In [187]:
# retriving only 2 columns from the dataset
print( df[['date','new_cases']])

           date  new_cases
0    2019-12-31        0.0
1    2020-01-01        0.0
2    2020-01-02        0.0
3    2020-01-03        0.0
4    2020-01-04        0.0
..          ...        ...
243  2020-08-30     1444.0
244  2020-08-31     1365.0
245  2020-09-01      996.0
246  2020-09-02      975.0
247  2020-09-03     1326.0

[248 rows x 2 columns]

In [188]:
df_copy = df.copy()  # shallow copy -> modification in one ds will not efect the other

In [189]:
#  toacces a specific row at a specifc locatio we use-> .loc

df.loc[243]

date          2020-08-30
new_cases         1444.0
new_deaths           1.0
new_tests        53541.0
Name: 243, dtype: object

In [190]:
df.at[243,'new_cases']

np.float64(1444.0)

In [191]:
total_new_cases = df.new_cases.sum()
total_new_cases

np.float64(271515.0)

In [192]:
total_deaths = df.new_deaths.sum()
total_deaths

np.float64(35497.0)

In [193]:
death_rate = total_deaths/total_new_cases * 100
print(f"{death_rate:.2f}")

13.07

In [194]:
# to find the num of deaths in july
july = df[(df.date >= '2020-07-01') & (df.date <= '2020-07-31')]
july

           date  new_cases  new_deaths  new_tests
183  2020-07-01      142.0        23.0    29325.0
184  2020-07-02      182.0        21.0    29147.0
185  2020-07-03      201.0        30.0    25680.0
186  2020-07-04      223.0        15.0    28946.0
187  2020-07-05      235.0        21.0    21166.0
188  2020-07-06      192.0         7.0    13771.0
189  2020-07-07      208.0         8.0    22490.0
190  2020-07-08      137.0        30.0    28679.0
191  2020-07-09      193.0        15.0    29947.0
192  2020-07-10      214.0        12.0    27251.0
193  2020-07-11      276.0        12.0    25449.0
194  2020-07-12      188.0         7.0    23061.0
195  2020-07-13      234.0         9.0    14006.0
196  2020-07-14      169.0        13.0    24222.0
197  2020-07-15      114.0        17.0    28392.0
198  2020-07-16      162.0        13.0    28089.0
199  2020-07-17      230.0        20.0    28661.0
200  2020-07-18      231.0        11.0    27569.0
201  2020-07-19      249.0        14.0    20621.0
202  2020-07-20      218.0         3.0    14121.0
203  2020-07-21      190.0        13.0    23915.0
204  2020-07-22      128.0        15.0    29288.0
205  2020-07-23      280.0         9.0    33018.0
206  2020-07-24      306.0        10.0    28970.0
207  2020-07-25      252.0         5.0    28059.0
208  2020-07-26      274.0         5.0    25177.0
209  2020-07-27      254.0         5.0    19374.0
210  2020-07-28      168.0         5.0    25341.0
211  2020-07-29      202.0        11.0    30875.0
212  2020-07-30      288.0         6.0    33396.0
213  2020-07-31      382.0         3.0    29686.0

In [195]:
july.sum()

date          2020-07-012020-07-022020-07-032020-07-042020-0...
new_cases                                                6722.0
new_deaths                                                388.0
new_tests                                              797692.0
dtype: object

In [196]:
# day with max cases
max_cases = max(df.new_cases)
max_cases

6557.0

In [197]:
# 10 days with highest num of cases
Ten_highest_cases = df.sort_values('new_cases',ascending = False).head(10)
Ten_highest_cases

          date  new_cases  new_deaths  new_tests
82  2020-03-22     6557.0       795.0        NaN
87  2020-03-27     6153.0       660.0        NaN
81  2020-03-21     5986.0       625.0        NaN
89  2020-03-29     5974.0       887.0        NaN
88  2020-03-28     5959.0       971.0        NaN
83  2020-03-23     5560.0       649.0        NaN
80  2020-03-20     5322.0       429.0        NaN
85  2020-03-25     5249.0       743.0        NaN
90  2020-03-30     5217.0       758.0        NaN
86  2020-03-26     5210.0       685.0        NaN

In [198]:
Ten_lowest_cases = df.sort_values('new_cases',ascending = True).head(10)
Ten_lowest_cases

           date  new_cases  new_deaths  new_tests
172  2020-06-20     -148.0        47.0    29875.0
0    2019-12-31        0.0         0.0        NaN
2    2020-01-02        0.0         0.0        NaN
1    2020-01-01        0.0         0.0        NaN
4    2020-01-04        0.0         0.0        NaN
5    2020-01-05        0.0         0.0        NaN
6    2020-01-06        0.0         0.0        NaN
3    2020-01-03        0.0         0.0        NaN
8    2020-01-08        0.0         0.0        NaN
9    2020-01-09        0.0         0.0        NaN

# ***data cleaning***

**Note** - Now here we have a negative value in new_case column which can be due go data entry error
this can be solved using:      
1.replace it with 0           
2.replace with average of entire column        
3.replace with avg of values on previous and next date            
4. discard the row entirely

In [199]:
# avg of new_cases
total_avg = df.new_cases.mean()
total_avg

np.float64(1094.8185483870968)

In [200]:
# avg of previous and next dates
negative_new_cases = df[df.new_cases < 0]
negative_new_cases

print(df.loc[171:173])

           date  new_cases  new_deaths  new_tests
171  2020-06-19      331.0        66.0    28570.0
172  2020-06-20     -148.0        47.0    29875.0
173  2020-06-21      264.0        49.0    24581.0

In [201]:
recent_avg = df.loc[171:173].new_cases.mean()-df.loc[172].new_cases
recent_avg

np.float64(297.0)

here we are replacing the negative value

In [202]:
# df.at[172,'new_cases'] = 0
# df.at[172,'new_cases'] = total_avg
# df.at[172,'new_cases'] = recent_avg

In [203]:
df.loc[172]

date          2020-06-20
new_cases         -148.0
new_deaths          47.0
new_tests        29875.0
Name: 172, dtype: object

In [204]:
negative_new_cases = df[df.new_cases < 0]
negative_new_cases

           date  new_cases  new_deaths  new_tests
172  2020-06-20     -148.0        47.0    29875.0

In [205]:
# to drop  the row entirely
# df.drop(172,inplace = True)

**Another way to replace the -ve values dynamically by using** ***mask()***

In [222]:
# lets add more -ve values
df.loc[22,'new_cases'] = -100
df.loc[44,'new_cases'] = -100
df.loc[df.new_cases < 0]

          date  new_cases  new_deaths  new_tests
22  2020-01-22     -100.0         0.0        NaN
44  2020-02-13     -100.0         0.0        NaN

In [224]:
df['new_cases'] = df['new_cases'].mask(df['new_cases'] < 0, 0)
                    # OR
# df.loc[df['new_cases'] < 0, 'new_cases'] = 0

convert to date time

In [225]:
# df.date = pd.to_datetime(df.date)
df.loc[df.new_cases < 0]

Empty DataFrame
Columns: [date, new_cases, new_deaths, new_tests]
Index: []

           date  new_cases  new_deaths  new_tests
0    2019-12-31        0.0         0.0        NaN
1    2020-01-01        0.0         0.0        NaN
2    2020-01-02        0.0         0.0        NaN
3    2020-01-03        0.0         0.0        NaN
4    2020-01-04        0.0         0.0        NaN
..          ...        ...         ...        ...
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    42583.0
245  2020-09-01      996.0         6.0    54395.0
246  2020-09-02      975.0         8.0        NaN
247  2020-09-03     1326.0         6.0        NaN

[248 rows x 4 columns]

In [233]:
df

           date  new_cases  new_deaths  new_tests
0    2019-12-31        0.0         0.0        NaN
1    2020-01-01        0.0         0.0        NaN
2    2020-01-02        0.0         0.0        NaN
3    2020-01-03        0.0         0.0        NaN
4    2020-01-04        0.0         0.0        NaN
..          ...        ...         ...        ...
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    42583.0
245  2020-09-01      996.0         6.0    54395.0
246  2020-09-02      975.0         8.0        NaN
247  2020-09-03     1326.0         6.0        NaN

[248 rows x 4 columns]